### ISSUE TITLE
By opening Applications Menu, Wingpanel begin to use too much memory

### ISSUE THREAD

**Issue by ryonakano** [elementary/applications-menu#117]
![screenshot from 2018-07-14 15-52-37](https://user-images.githubusercontent.com/26003928/42722327-313cbd92-8785-11e8-933b-e6a5ba91281b.png)

By opening Applications Menu, Wingpanel begin to use too much memory on a system with LibreOffice.

## Steps to reproduce the behavior

1. Prepare a fresh install Juno ~~Beta1~~ and update the system
2. Run `sudo apt install libreoffice`
3. Open Applications menu
4. Wingpanel began to use over **200MB** memory (in usual it spends only around 10MB memory)

Opening another indicator happens nothing. Only by opening Applications Menu.

I'm not sure this issue is due to either Wingpanel, Applications Menu, or LibreOffice.

**Comment by peteruithoven** [comment]
I've noticed some switchboard plug's execute some logic. They are included to enable settings search (switchboard-plugin). Also see: https://github.com/elementary/applications-menu/issues/83
It might be interesting to disable some plugins and compare the effect. 

Is the memory usage only higher while the Applications menu is open or does it remain high after it's been opened once?  

I can't reproduce the issue btw, it's on a stable 80 - 85MB. I've installed LibreOffice. What happens when you remove libreoffice?.

33MB to 60MB without libreoffice. 
After installing it starts at 33MB. After opening it it goes to 62MB. But when I then visit the Office category (where the icons of Libreoffice are) it jumps to 221MB.

If you want to test this, you can restart Winganel by running `killall wingpanel`.

**Comment by peteruithoven** [comment]
According to David Hewitt we might be able to track this down with Valgrind or Heaptrack.

**Comment by peteruithoven** [comment]
Checking the icon info in Granite.AsyncImage: https://github.com/elementary/granite/blob/master/lib/Widgets/AsyncImage.vala#L319 (which is used to load the icon images) I can confirm svg versions of the icons are loaded. For example: `/usr/share/icons/gnome/scalable/apps/libreoffice-writer.svg` (which symlinks to `/usr/share/icons/hicolor/scalable/apps/libreoffice-writer.svg`)

Omg, `libreoffice-calc.svg` is 1.3MB!
```
/usr/share/icons/hicolor/scalable/apps$ ll -h | grep libreoffice
-rw-r--r--  1 root root 465K aug 30 11:49 libreoffice-base.svg
-rw-r--r--  1 root root 1,3M aug 30 11:49 libreoffice-calc.svg
-rw-r--r--  1 root root 624K aug 30 11:49 libreoffice-draw.svg
-rw-r--r--  1 root root 550K aug 30 11:49 libreoffice-impress.svg
-rw-r--r--  1 root root 142K aug 30 11:49 libreoffice-main.svg
-rw-r--r--  1 root root 659K aug 30 11:49 libreoffice-math.svg
-rw-r--r--  1 root root 142K aug 30 11:49 libreoffice-startcenter.svg
-rw-r--r--  1 root root 534K aug 30 11:49 libreoffice-writer.svg
```

There is a [flag to disable svg's](https://valadoc.org/gtk+-3.0/Gtk.IconLookupFlags.html) in general, but we use svg's for icon's a lot, so that's really not an option.

**Comment by peteruithoven** [comment]
Looks like there is a fixed & relevant Libreoffice  issue: https://bugs.documentfoundation.org/show_bug.cgi?id=98141

**Comment by peteruithoven** [comment]
If I don't load icons by commenting:
https://github.com/elementary/granite/blob/master/lib/Widgets/AsyncImage.vala#L326-L337
the memory usage remains somewhere between 37 - 44MB.

If I just disable creating the surface and caching:
https://github.com/elementary/granite/blob/master/lib/Widgets/AsyncImage.vala#L333-L337
it still sky rockets to 200MB+, which seems like a huge memory leak?

**Comment by peteruithoven** [comment]
I opened a Granite issue: https://github.com/elementary/granite/issues/223

**Comment by peteruithoven** [comment]
It's easy to reproduce by running the following script made by @donadigo:

```
static bool use_async = true;

public static int main (string[] args) {
    Gtk.init (ref args);
    var theme = Gtk.IconTheme.get_default ();

    List<unowned string> icons = theme.list_icons (null);
    var infos = new List<Gtk.IconInfo> ();
    foreach (string icon in icons) {
        infos.append (theme.lookup_icon (icon, 64, 0));
    }

    var pixbufs = new List<Gdk.Pixbuf> ();
    if (use_async) {
        foreach (unowned Gtk.IconInfo info in infos) {
            info.load_icon_async.begin (null, (obj, res) => {
                var pix = info.load_icon_async.end (res);
                pixbufs.append (pix);
                print (pixbufs.length ().to_string () + "\n");
            });
        }
    } else {
        foreach (unowned Gtk.IconInfo info in infos) {
            pixbufs.append(info.load_icon ());
            print (pixbufs.length ().to_string () + "\n");
        }
    }

    Gtk.main ();
    return 0;
}
```

Compile & run:
```
valac --pkg gtk+-3.0 test.vala
./test
```
See difference between memory usage when toggling: `use_async`.

**Comment by ryonakano** [comment]
I can no longer reproduce this issue on Odin Daily. Wingpanel only consumes around 10 MB on init and around 20 MB after opening it. Closing.
