### ISSUE TITLE
Shortcut Tooltip doesn't show for overlay key

### ISSUE THREAD

**Issue by ghost** [elementary/applications-menu#184]

**Comment by CallieG** [comment]
So, I chose to alter my Applications-Menu keyboard shortcut to use solely the <meta> key by itself, yet on mouseover it reflects the default shortcuts, <meta>+space and Alt+F2.

Not a deal breaker for usage, but possibly a stumbling block for new users that could make them think their choice was not respected by the system.

**Comment by peteruithoven** [comment]
Looks like https://github.com/elementary/applications-menu/pull/162 didn't fix all cases. 
It monitors setting the shortcut here:
![screenshot from 2019-02-11 20-16-09](https://user-images.githubusercontent.com/523210/52587361-224d8f80-2e3a-11e9-9add-aa7215d54b1d.png)
But not here:
![screenshot from 2019-02-11 20-16-22](https://user-images.githubusercontent.com/523210/52587349-1cf04500-2e3a-11e9-8435-918ed65a14c9.png)
Probably because it's a different setting?

**Comment by peteruithoven** [comment]
The other setting: `/org/pantheon/desktop/gala/behavior/overlay-action`, it's set here:
https://github.com/elementary/switchboard-plug-keyboard/blob/483f8b0e7f238bf9d3c8cfdc975fe1854b6b0788/src/Views/Layout.vala#L183-L193

**Comment by zeebok** [comment]
I looked into this. Functionally I have it working, checking the keyboard-plug's setting, but when I want to have it add the accelerator I run into an issue. The string cannot just be "⌘"  or else nothing shows up. If I use "<S

**Comment by cassidyjames** [comment]
@zeebok ah that might be a bug in Granite, then, if it doesn't accept Super alone as a valid key?

**Comment by zeebok** [comment]
Depends on your definition of accept. It doesn't error but it does force a '+' to be appended. I will take a look at Granite and see what I can kind see!

**Comment by zeebok** [comment]
Yep Granite **does** automatically add " + " to any modifier sent as an accel. I realized I can work around this, and simply add the super character to the tooltip when it sees the system setting set. Does order of the shortcut keys matter?

**Comment by ryonakano** [comment]
Fixed in #480, thank you @zeebok!
