### ISSUE TITLE
Browser should be named Browser, not some "Epiphany"

### ISSUE THREAD

**Issue by uncertainquark** [elementary/applications-menu#187]
All apps in elementary are given generic names for sound reasons. Why is then the browser, arguably among the most used app, using the name "Epiphany" instead of just "Browser"? 

![screenshot from 2019-02-27 07-09-28](https://user-images.githubusercontent.com/22585732/53475074-03cfd100-3a95-11e9-8215-0a27b308c2bb.png)

For all new to elementary users the older users especially, the generic application names are a boon.

**Comment by peteruithoven** [comment]
I'm assuming this is because Epiphany is a "external" project.
https://gitlab.gnome.org/GNOME/epiphany/

**Comment by uncertainquark** [comment]
Is it not possible to change the name that elementary shows in the app launcher?

**Comment by ryonakano** [comment]
Related: https://github.com/elementary/default-settings/issues/96

**Comment by peteruithoven** [comment]
I think it's more than related? I'm closing this one in favor of: https://github.com/elementary/default-settings/issues/96

@uncertainquark Names in the Applications menu are retrieved from the .desktop files from applications. AppEditor is an easy to use application if you want to have a look at those files.

@uncertainquark Sorry for closing so many of your issues, I really appreciate your input, but we have to be quite strict in order to keep the issue queues somewhat maintainable.

**Comment by alexmex90** [comment]
> I'm assuming this is because Epiphany is a "external" project.
> https://gitlab.gnome.org/GNOME/epiphany/
> 
> Looks like another external project, the Document Viewer, which is actually called Evince, has renamed itself for launchers like our Application menu: https://gitlab.gnome.org/GNOME/evince/blob/master/data/org.gnome.Evince.desktop.in.in#L2

Epiphany is a code name for development. The application is actually called Web.

https://wiki.gnome.org/Apps/Web/
