### ISSUE TITLE
[Feature Request] "Reveal in File Browser" when right-clicking app icons in the Dock

### ISSUE THREAD

**Issue by a-tokarev** [elementary/applications-menu#203]
Suggestion: implement "**Reveal in File Browser**" menu item, when right-clicking any application's icon in the Dock. 
Very useful for quick location of the installed apps or their directories.

[!] I know this has nothing to do with Applications-Menu. Sorry guys, couldn't find the Dock section. Does it exist? If so, please move it there. Thank you very much!

**Comment by danrabbit** [comment]
Closing because this is not technically possible. When you install an application, it isn't a single file that gets placed in one location. There is a binary that goes to `/usr/bin`, a .desktop file that goes to `/usr/share/applications`, an appdata file that goes to `/usr/share/metainfo`, etc etc. So there's no way to show where an app is; its in a lot of places
