### ISSUE TITLE
Juno's "Applications" menu doesn't show Snap or Flatpak apps

### ISSUE THREAD

**Issue by jebeld17** [elementary/applications-menu#230]
Flatpak nor Snapcraft apps show up in the "Applications" menu in ElementaryOS Juno.
Please fix.

**Comment by danrabbit** [comment]
I can't confirm this. I have both snaps and flatpaks showing in the menu. Can you provide more information about what specific programs are having problems and how you installed them?

**Comment by cassidyjames** [comment]
@jebeld17 when first installing a Snap or Flatpak app, I believe Snap and Flatpak update the path for application launchers, which requires a log out and log back in for them to show up in the Applications Menu. However, future installations should show up immediately since the path has been updated. Can you confirm that?

**Comment by jebeld17** [comment]
I think I figured out the issue, at least on my end:
The apps will show up, but only after a reboot.

Now I don't know if it is, but if the Applications menu is generated
through periodic scans, maybe some adjustments to the time period between
scans should be made?

**Comment by cassidyjames** [comment]
@jebeld17 as I mentioned, this is only an issue the first time you install either a Flatpak or Snap app, as Flatpak and Snap themselves are updating the path for installed application launchers. Once that path is added, future apps show up on demand. I don't _think_ there's anything reasonable we can do in this codebase to always check if the path has changed (as that's an uncommon thing to happen, usually).
