### ISSUE TITLE
Add non-paginated, vertically scrolling view

### ISSUE THREAD

**Issue by panicsteve** [elementary/applications-menu#337]
## Prerequisites
- [X] I have searched open and closed issues for duplicates.

#124 is tangentially related, but I don't think this is a duplicate.

## Feature
**Is your feature request related to a problem? Please describe.**

I find it confusing when using a mouse with the application menu in grid view that the mousewheel (vertically oriented) scrolls horizontally through a paginated list.  Two reasons:

1. It's scrolling on the wrong axis compared to my physical input
2. The pagination feels like an artificial restriction. Why are there pages at all, vs. free scrolling?

The horizontal paginated design evokes something like the iPhone home screen to me, and feels out of place in a (usually) non-touch user interface paradigm.

**Describe the solution you'd like**

To my brain, at least, in the context of using a traditional mouse with a vertical wheel, it would make sense to have a grid view that scrolled only vertically, with no pagination.  I'm not sure if this should replace the existing grid view, or be a new, third view option.

**Comment by danrabbit** [comment]
The category view now behaves exactly like this in master, so I think this is probably solved. Closing since the next release will offer a view that is more of a traditional menu with categories and scrolling.

In the grid view we use pages based on some user research with regards to finding the thing you're looking for the fastest. We looked at users' ability to locate specific icons within a grid and found a place where that ability sharply drops off at a certain grid side. Pages make it easy to filter down so that you can remember an app is on a specific page and find where it is on that page spatially very quickly. This is unlike a scrolling view where items that appear after "the fold" are never in a spatially consistent position so you have to hunt for them each time.
