### ISSUE TITLE
Launch an application using GPU

### ISSUE THREAD

**Issue by ma1onso** [elementary/applications-menu#394]
Hi, elementary devs,

With the new Gnome version (3.36) is possible to run an application using the GPU from the application list.

"Users of NVIDIA’s proprietary drivers will be able to launch applications using the discrete GPU from within GNOME Shell now, via the “Launch on Discrete GPU” menu item." https://help.gnome.org/misc/release-notes/3.36/

![image](https://user-images.githubusercontent.com/1877511/83373404-d788bb80-a38d-11ea-9323-5d1ca5e6a947.png)

Plans for elementary os implementation?

**Comment by danrabbit** [comment]
It looks like [Desktop Entry 1.4](https://specifications.freedesktop.org/desktop-entry-spec/desktop-entry-spec-latest.html#idm45534318958976) added a key `PrefersNonDefaultGPU`, so I'm not sure a menu item is necessary anymore.

It would be interesting to hear from someone GNOME side about their plans for this and why they chose to add a menu item here

**Comment by ma1onso** [comment]
The Linux mint implementation is the same as Gnome 3.36 🌊 

![image](https://user-images.githubusercontent.com/1877511/83469432-4e34c000-a445-11ea-98d2-c57a437e9778.png)

https://blog.linuxmint.com/?p=3906

**Comment by cassidyjames** [comment]
@danrabbit I think the case is for multiple GPUs? It looks like macOS also has a similar option, but I'm not a multi-GPU user so I'm not super familiar with this. https://support.apple.com/en-us/HT208544

**Comment by ma1onso** [comment]
@danrabbit http://www.hadess.net/2020/05/dual-gpu-support-launch-on-discrete-gpu.html more information about **PrefersNonDefaultGPU**

**Comment by jhaygood86** [comment]
@danrabbit The desktop entry shows the "default" GPU to launch on. The idea is to allow the user to override if the developer hasn't gotten around to adding sane defaults.

**Comment by jhaygood86** [comment]
I took a first stab of this in #425 

I have an Alienware m15 that runs at a gazillion degrees and a 5 minute battery when NVIDIA is enabled, but many things are unusable with the Intel being the only active GPU. Leaving it in "on-demand" mode works fine, but there are times I want my apps to have a bit more "umph". Not very many apps opt in to the default setting, so having the context menu is preferred. I used the same wording as GNOME upstream. We can adjust (i.e., go with the MATE / Windows approach of listing the GPU name instead of "Discrete" and "Integrated") or some other alternative. It's a relatively advanced feature, but one that is quite needed on hybrid graphics systems.

**Comment by marcelovbcfilho** [comment]
Would love to see this implemented, I'm using a notebook with dual graphics card (intel + nvidia, a very notebook common configuration) and always (if "on demand" prime profile is on, that is most of the time to save some power and avoid heat) when I want to play some games I need to run the app in the command line using the following and it's a very boring process, there is a strategy to implement this feature ?
```
__NV_PRIME_RENDER_OFFLOAD=1 __GLX_VENDOR_LIBRARY_NAME=nvidia command_name arguments
``` 
Command reference: https://starbeamrainbowlabs.com/blog/article.php?article=posts%2F436-running-application-on-nvidia.html
