### ISSUE TITLE
Problema con accesos directos

### ISSUE THREAD

**Issue by josemanuelases** [elementary/applications-menu#458]
Buenas tardes,

Les notifico que estoy usando la útlima versión de ELEMENTARY OS HERA.
Encuentro un problema siempre que enciendo el ordenador.
Tengo unos acceso directos en el escritorio y los que no corresponden al disco /home no aparecen.
Para que aparezcan tengo que entrar en el gestor de archivos, entrar en cada una de las unidades distintas al /home.
Despues de hacer esto si aparecen.
Les mando una captura de pantalla para que vean como está al iniciar.

![Captura realizada el 2021-01-29 18 45 07](https://user-images.githubusercontent.com/23087584/106309738-d6809480-6262-11eb-8ef8-450b1687ca31.png)

Espero que se pueda solucionar esta incidencia ya que es molesto tener que hacer el proceso todas las veces que arranco el ordenador

Aparte de esto estoy encantado con esta distribución.

Muchas gracias por vuestro trabajo.
Un saludo.
José Manuel Ases.

**Comment by danrabbit** [comment]
Thanks for your issue report! elementary OS doesn't ship with a program that draws icons on the desktop, so you will need to report this issue against whichever software you've installed to do this.

Closing as "Out of scope" since this is an issue in a 3rd party program and not something maintained by elementary
