### ISSUE TITLE
Only searches switchboard plug titles instead of plug content

### ISSUE THREAD

**Issue by davidmhewitt** [elementary/applications-menu#49]
Originally raised here with the example of searching for "firewall" doesn't yield the "Security & Privacy" plug: https://github.com/elementary/switchboard-plug-security-privacy/issues/30

Looking through the code, it seems that the applications menu is only searching for plug titles rather than plug contents by using the search API in switchboard:

https://github.com/elementary/applications-menu/blob/master/lib/synapse-plugins/switchboard-plugin.vala#L140

**Comment by peteruithoven** [comment]
This is partly fixed with: https://github.com/elementary/applications-menu/pull/133
Although, currently, it ignores the 3th level of results, ignoring for example:
```
Desktop → Dock → Display: dock
Desktop → Dock → Hide Mode: dock
Desktop → Dock → Icon Size: dock
Desktop → Dock → Theme: dock
```

More info: https://github.com/elementary/applications-menu/issues/94#issuecomment-425161136

We might be able to include more levels if we adjust the search function in the switchboard-plugin.

**Comment by peteruithoven** [comment]
This could be fixed by: https://github.com/elementary/applications-menu/pull/142

**Comment by danrabbit** [comment]
Gonna close this since the portion of this that is the application menu's responsibility is merged. Just need to merge branches into the plugs now
