### ISSUE TITLE
Add search icon to beginning indicator

### ISSUE THREAD

**Issue by cassidyjames** [elementary/applications-menu#60]
Since we want to be consistently using the word "apps", and adding a search icon could better expose the search function.

**Comment by danrabbit** [comment]
Something to consider is that there isn't really anything else on this side of the panel and a longer label gives a larger click target

**Comment by lainsce** [comment]
![](https://i.imgur.com/pAh130n.jpg)

Visual mockup for this, for anyone that wants to implement this. Dotted box around the indicator would be the clickable area.

**Comment by tintou** [comment]
FYI: the label will remain at the same size in other languages as there is not always a diminutive for Applications

**Comment by Astro-City** [comment]
I would not do this.  

Applications is self explanatory, you click it to have access to your applications.  Since it's a big word it even make things symmetric.

**Comment by J0Ar** [comment]
Like Tintou said...here in germany we don't have a diminution for 'Applications' ...we just say 'Anwendungen' or 'Programme'  
The people here are using the words 'App' and 'Apps' most of the time for applications on smartphones...so it's something like a proper noun for this specified group of applcations. > Small device...short word :sweat_smile: 
 I mean, they do not translate 'App(s)' from english to german because everyone think about Applications on smartphones.

**Comment by snowparrot** [comment]
To extent J0Ar's argument: Don't use Apps just for design reasons because the German translation might still the same. Better to see this discussion as English-only one.
